
auth.token=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

defaults.org=pladomus
defaults.project=pladomus-frontend-app

defaults.url=https://sentry.io/
