import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// One sidebar per top-level docs/ folder, each autogenerated from the
// filesystem — ordering comes from each folder's _category_.json `position`
// and each page's `sidebar_position` frontmatter.
const sidebars: SidebarsConfig = {
  gettingStartedSidebar: [{type: 'autogenerated', dirName: 'getting-started'}],
  architectureSidebar: [{type: 'autogenerated', dirName: 'architecture'}],
  screensSidebar: [{type: 'autogenerated', dirName: 'screens'}],
  nativeBridgeSidebar: [{type: 'autogenerated', dirName: 'native-bridge'}],
  conventionsSidebar: [{type: 'autogenerated', dirName: 'conventions'}],
  referenceSidebar: [{type: 'autogenerated', dirName: 'reference'}],
};

export default sidebars;
